; CharacterSkin
namespace = Creator\Character\ModName

; Constants -------------------------

[Constants]
global $active = 0

; =======================================
; Variables
global persist $shoes = 0
global persist $innerskirt = 0
global persist $innerskirt_transparency = 0
global persist $backskirt = 0
global persist $backskirt_transparency = 0
global persist $dress = 0
global persist $hair = 0
global persist $skirt_color = 0
global persist $under_color = 0
global persist $top = 0
global persist $tail = 0

; =======================================
; Help Menu
global $helpVisible = 0
global persist $helpScale = 1
global $menuOff = 1
global $menuTimeout
global $detect_lock
global persist $lock = 0

[Present]
;Turns off menu when character is inactive
if $active == 0 && $helpVisible == 1
    post $helpVisible = 0
    run = CommandListHelp
endif

;Turns off small pop-up menu after set amount of time
if $menuOff == 0
    if TIME - $menuTimeout >= 1.2
        post $menuOff = 1
        post Resource\ShaderFixes\help.ini\Help = null
    endif
endif
post $active = 0

; ====================================================
; MENU KEYS

[KeySwapMenu]
key = ALT H
condition = $active == 1
type = cycle
$helpVisible = 0, 1
run = CommandListHelp

[KeySwapMenuScale]
key = ALT Y
condition = $active == 1
type = cycle
$helpScale = 1, 3, 2
run = CommandListHelpUpdate

; ====================================================
; VARIABLE KEYS

[KeySwapLockToggles]
key = VK_UP
condition = $active == 1
type = cycle
$lock = 0, 1
$detect_lock = 1
run = CommandListHelpUpdate

; ====================================================

[KeySwapShoes]
key = 5
condition = $active == 1 && $lock == 0
type = cycle
$shoes = 0, 1

[KeySwapInnerskirt]
key = no_ctrl 6
condition = $active == 1 && $lock == 0
type = cycle
$innerskirt = 0, 1, 2, 3, 4, 5, 6

[KeyInnerskirtTransparency]
key = ctrl 6
condition = $active == 1 && $lock == 0
type = cycle
$innerskirt_transparency = 0, 1

[KeySwapBackskirt]
key = no_ctrl 7
condition = $active == 1 && $lock == 0
type = cycle
$backskirt = 0, 1, 2, 3

[KeyBackskirtTransparency]
key = ctrl 7
condition = $active == 1 && $lock == 0
type = cycle
$backskirt_transparency = 0, 1

[KeySwapSkirtColor]
key = ctrl 8
condition = $active == 1 && $lock == 0
type = cycle
$skirt_color = 0, 1

[KeySwapDress]
key = no_ctrl 8
condition = $active == 1 && $lock == 0
type = cycle
$dress = 0, 1, 2

[KeySwapUnderColor]
key = ctrl 9
condition = $active == 1 && $lock == 0
type = cycle
$under_color = 0, 1, 2, 3

[KeySwapHair]
key = no_ctrl 9
condition = $active == 1 && $lock == 0
type = cycle
$hair = 0, 1, 2

[KeySwapTop]
key = no_modifiers 0
condition = $active == 1 && $lock == 0
type = cycle
$top = 0, 1

[KeySwapTail]
key = ctrl 0
condition = $active == 1 && $lock == 0
type = cycle
$tail = 0, 1

; Custom Shaders -------------------------

[CustomShaderInnerSkirtSemiTransparentWhite]
blend = ADD BLEND_FACTOR INV_BLEND_FACTOR
blend_factor[0] = 0.75
blend_factor[1] = 0.75
blend_factor[2] = 0.75
blend_factor[3] = 1
if $innerskirt == 0
    ; InnerSkirt_01
    drawindexed = 1227, 33057, 0
else if $innerskirt == 1
    ; InnerSkirt_02
    drawindexed = 1302, 34284, 0
else if $innerskirt == 2
    ; InnerSkirt_03
    drawindexed = 1227, 35586, 0
else if $innerskirt == 3
    ; InnerSkirt_04
    drawindexed = 1302, 36813, 0
else if $innerskirt == 4
    ; InnerSkirt_05
    drawindexed = 1227, 38115, 0
else if $innerskirt == 5
    ; InnerSkirt_06
    drawindexed = 1302, 39342, 0
endif

[CustomShaderInnerSkirtSemiTransparentBlack]
blend = ADD BLEND_FACTOR INV_BLEND_FACTOR
blend_factor[0] = 0.95
blend_factor[1] = 0.95
blend_factor[2] = 0.95
blend_factor[3] = 1
if $innerskirt == 0
    ; InnerSkirt_01
    drawindexed = 1227, 33057, 0
else if $innerskirt == 1
    ; InnerSkirt_02
    drawindexed = 1302, 34284, 0
else if $innerskirt == 2
    ; InnerSkirt_03
    drawindexed = 1227, 35586, 0
else if $innerskirt == 3
    ; InnerSkirt_04
    drawindexed = 1302, 36813, 0
else if $innerskirt == 4
    ; InnerSkirt_05
    drawindexed = 1227, 38115, 0
else if $innerskirt == 5
    ; InnerSkirt_06
    drawindexed = 1302, 39342, 0
endif

[CustomShaderBackSkirtSemiTransparentWhite]
blend = ADD BLEND_FACTOR INV_BLEND_FACTOR
blend_factor[0] = 0.75
blend_factor[1] = 0.75
blend_factor[2] = 0.75
blend_factor[3] = 1
if $backskirt == 0
    ; BackSkirt_01
    drawindexed = 168, 21093, 0
else if $backskirt == 1
    ; BackSkirt_02
    drawindexed = 174, 21261, 0
else if $backskirt == 2
    ; BackSkirt_03
    drawindexed = 168, 21435, 0
else if $backskirt == 3
    ; BackSkirt_04
    drawindexed = 174, 21603, 0
endif

[CustomShaderBackSkirtSemiTransparentBlack]
blend = ADD BLEND_FACTOR INV_BLEND_FACTOR
blend_factor[0] = 0.95
blend_factor[1] = 0.95
blend_factor[2] = 0.95
blend_factor[3] = 1
if $backskirt == 0
    ; BackSkirt_01
    drawindexed = 168, 21093, 0
else if $backskirt == 1
    ; BackSkirt_02
    drawindexed = 174, 21261, 0
else if $backskirt == 2
    ; BackSkirt_03
    drawindexed = 168, 21435, 0
else if $backskirt == 3
    ; BackSkirt_04
    drawindexed = 174, 21603, 0
endif

; Texture Sets -------------------------

[CommandListSkinTextures]
Resource\MI\Diffuse = ref ResourceCharacterSkinBodyADiffuse
Resource\MI\NormalMap = ref ResourceCharacterSkinBodyANormalMap
Resource\MI\LightMap = ref ResourceCharacterSkinBodyALightMap
Resource\MI\MaterialMap = ref ResourceCharacterSkinBodyAMaterialMap
run = CommandList\MI\SetTextures

[CommandListSkinTexturesBlack]
Resource\MI\Diffuse = ref ResourceCharacterSkinBodyADiffuse_Black
Resource\MI\NormalMap = ref ResourceCharacterSkinBodyANormalMap
Resource\MI\LightMap = ref ResourceCharacterSkinBodyALightMap
Resource\MI\MaterialMap = ref ResourceCharacterSkinBodyAMaterialMap
run = CommandList\MI\SetTextures

[CommandListExtraTextures]
Resource\MI\Diffuse = ref ResourceCharacterSkinExtraDiffuse
Resource\MI\NormalMap = ref ResourceCharacterSkinExtraNormalMap
Resource\MI\LightMap = ref ResourceCharacterSkinExtraLightMap
Resource\MI\MaterialMap = ref ResourceCharacterSkinExtraMaterialMap
run = CommandList\MI\SetTextures

[CommandListTailTextures]
Resource\MI\Diffuse = ref ResourceCharacterSkinTailDiffuse
Resource\MI\NormalMap = ref ResourceCharacterSkinTailNormalMap
Resource\MI\LightMap = ref ResourceCharacterSkinTailLightMap
Resource\MI\MaterialMap = ref ResourceCharacterSkinTailMaterialMap
run = CommandList\MI\SetTextures

; Overrides -------------------------

[TextureOverrideCharacterSkinBodyBlend]
hash = 5121459b
handling = skip
vb2 = ResourceCharacterSkinBodyBlend
if DRAW_TYPE == 1
    vb0 = ResourceCharacterSkinBodyPosition
    draw = 29258, 0
endif

[TextureOverrideCharacterSkinBodyTexcoord]
hash = 01c36f40
vb1 = ResourceCharacterSkinBodyTexcoord

[TextureOverrideCharacterSkinBodyVertexLimitRaise]
hash = a4a705f6
override_vertex_count = 29258
override_byte_stride = 40

[TextureOverrideCharacterSkinDressBlend]
hash = 958db681
handling = skip
vb2 = ResourceCharacterSkinDressBlend
if DRAW_TYPE == 1
    vb0 = ResourceCharacterSkinDressPosition
    draw = 13663, 0
endif

[TextureOverrideCharacterSkinDressTexcoord]
hash = 6eb82b02
vb1 = ResourceCharacterSkinDressTexcoord

[TextureOverrideCharacterSkinDressVertexLimitRaise]
hash = 467f402c
override_vertex_count = 13663
override_byte_stride = 40

[TextureOverrideCharacterSkinHairBlend]
hash = 28a01b2c
handling = skip
vb2 = ResourceCharacterSkinHairBlend
if DRAW_TYPE == 1
    vb0 = ResourceCharacterSkinHairPosition
    draw = 13039, 0
endif

[TextureOverrideCharacterSkinHairTexcoord]
hash = b8cb383f
vb1 = ResourceCharacterSkinHairTexcoord

[TextureOverrideCharacterSkinHairVertexLimitRaise]
hash = d011ed6c
override_vertex_count = 13039
override_byte_stride = 40

[TextureOverrideCharacterSkinBodyIB]
hash = a913e9a9
handling = skip

[TextureOverrideCharacterSkinBodyA]
$active = 1
hash = a913e9a9
match_first_index = 0
ib = ResourceCharacterSkinBodyAIB
run = CommandListSkinTextures
; CharacterSkinBodyA-vb0=6567066b.txt (12946)
drawindexed = 35520, 0, 0

if $under_color == 0 || $under_color == 1
    ; Legs_01
    drawindexed = 7116, 48354, 0
else if $under_color == 2
    run = CommandListExtraTextures
    ; Legs_02
    run = CommandListExtraTextures
    ; Legs_03
    drawindexed = 6522, 62154, 0
    run = CommandListSkinTextures
endif

if $hair == 0
    ; HairAccessory_01 (373)
    drawindexed = 1266, 39408, 0
    ; HairFlower_01
    drawindexed = 3840, 40674, 0
else if $hair == 1 || $hair == 2
    ; HairFlower_02
    drawindexed = 3840, 44514, 0
endif

if $under_color == 3
    run = CommandListSkinTexturesBlack
else
    run = CommandListSkinTextures
endif

if $shoes == 0
    ; Shoes_01 (2368)
    drawindexed = 8940, 68676, 0
else if $shoes == 1
    ; Shoes_02 (2326)
    drawindexed = 8634, 77616, 0

    if $under_color < 3
        run = CommandListExtraTextures
        ; Toes_01
        drawindexed = 2751, 86250, 0
    else if $under_color == 3
        run = CommandListExtraTextures
        ; Toes_02
        drawindexed = 8061, 89001, 0
    endif
endif

if $top == 1
    run = CommandListExtraTextures
    ; Top_01
    drawindexed = 3888, 35520, 0
endif

[TextureOverrideCharacterSkinDressIB]
hash = fbb18630
handling = skip

[TextureOverrideCharacterSkinDressA]
$active = 1
hash = fbb18630
match_first_index = 0
ib = ResourceCharacterSkinDressAIB
if $skirt_color == 0
    Resource\MI\Diffuse = ref ResourceCharacterSkinDressADiffuse
else if $skirt_color == 1
    Resource\MI\Diffuse = ref ResourceCharacterSkinDressADiffuse_Black
endif
Resource\MI\NormalMap = ref ResourceCharacterSkinDressANormalMap
Resource\MI\LightMap = ref ResourceCharacterSkinDressALightMap
Resource\MI\MaterialMap = ref ResourceCharacterSkinDressAMaterialMap
run = CommandList\MI\SetTextures
; CharacterSkinDressA

; CharacterSkinDressA-vb0=c2b0eca3.txt (5559)
drawindexed = 21093, 0, 0

if $dress == 0
    if $top == 0
        ; Dress_01 (819)
        drawindexed = 2079, 21777, 0
    else if $top == 1
        ; Dress_01_Window
        drawindexed = 2061, 23856, 0
    endif
else if $dress == 1
    if $top == 0
        ; Dress_02 (820)
        drawindexed = 2079, 25917, 0
    else if $top == 1
        ; Dress_02_Window
        drawindexed = 2061, 27996, 0
    endif
else if $dress == 2
    if $top == 0
        ; Dress_03 (819)
        drawindexed = 1509, 30057, 0
    else if $top == 1
        ; Dress_03_Window
        drawindexed = 1491, 31566, 0
    endif
endif

if $innerskirt_transparency == 1
    if $skirt_color == 0
        run = CustomShaderInnerSkirtSemiTransparentWhite
    else if $skirt_color == 1
        run = CustomShaderInnerSkirtSemiTransparentBlack
    endif
else if $innerskirt == 0
    ; InnerSkirt_01 (383)
    drawindexed = 1227, 33057, 0
else if $innerskirt == 1
    ; InnerSkirt_02
    drawindexed = 1302, 34284, 0
else if $innerskirt == 2
    ; InnerSkirt_03
    drawindexed = 1227, 35586, 0
else if $innerskirt == 3
    ; InnerSkirt_04
    drawindexed = 1302, 36813, 0
else if $innerskirt == 4
    ; InnerSkirt_05
    drawindexed = 1227, 38115, 0
else if $innerskirt == 5
    ; InnerSkirt_06
    drawindexed = 1302, 39342, 0
endif

if $backskirt_transparency == 1
    if $skirt_color == 0
        run = CustomShaderBackSkirtSemiTransparentWhite
    else if $skirt_color == 1
        run = CustomShaderBackSkirtSemiTransparentBlack
    endif
else if $backskirt == 0
    ; BackSkirt_01 (383)
    drawindexed = 168, 21093, 0
else if $backskirt == 1
    ; BackSkirt_02
    drawindexed = 174, 21261, 0
else if $backskirt == 2
    ; BackSkirt_03
    drawindexed = 168, 21435, 0
else if $backskirt == 3
    ; BackSkirt_04
    drawindexed = 174, 21603, 0
endif

if $tail == 1
    run = CommandListTailTextures
    ; Tail_01
    drawindexed = 5202, 40644, 0
endif

[TextureOverrideCharacterSkinHairIB]
hash = ecaf558f
handling = skip

[TextureOverrideCharacterSkinHairA]
$active = 1
hash = ecaf558f
match_first_index = 0
ib = ResourceCharacterSkinHairAIB
Resource\MI\Diffuse = ref ResourceCharacterSkinHairADiffuse
Resource\MI\NormalMap = ref ResourceCharacterSkinHairANormalMap
Resource\MI\LightMap = ref ResourceCharacterSkinHairALightMap
Resource\MI\MaterialMap = ref ResourceCharacterSkinHairAMaterialMap
run = CommandList\MI\SetTextures

if $hair == 0
    ; Hair_01 (4100)
    drawindexed = 14916, 0, 0
else if $hair == 1
    ; Hair_02
    drawindexed = 10968, 14916, 0
else if $hair == 2
    ; Hair_03
    drawindexed = 10968, 25884, 0
endif

[TextureOverrideCharacterSkinHairB]
hash = ecaf558f
match_first_index = 14916
ib = ResourceCharacterSkinHairBIB

; CharacterSkinHairB-ib=ecaf558f.txt
drawindexed = 6702, 0, 0

; Resources -------------------------

[ResourceCharacterSkinBodyPosition]
type = Buffer
stride = 40
filename = CharacterSkinBodyPosition.buf

[ResourceCharacterSkinBodyBlend]
type = Buffer
stride = 32
filename = CharacterSkinBodyBlend.buf

[ResourceCharacterSkinBodyTexcoord]
type = Buffer
stride = 20
filename = CharacterSkinBodyTexcoord.buf

[ResourceCharacterSkinBodyAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = CharacterSkinBodyA.ib

[ResourceCharacterSkinDressPosition]
type = Buffer
stride = 40
filename = CharacterSkinDressPosition.buf

[ResourceCharacterSkinDressBlend]
type = Buffer
stride = 32
filename = CharacterSkinDressBlend.buf

[ResourceCharacterSkinDressTexcoord]
type = Buffer
stride = 20
filename = CharacterSkinDressTexcoord.buf

[ResourceCharacterSkinDressAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = CharacterSkinDressA.ib

[ResourceCharacterSkinHairPosition]
type = Buffer
stride = 40
filename = CharacterSkinHairPosition.buf

[ResourceCharacterSkinHairBlend]
type = Buffer
stride = 32
filename = CharacterSkinHairBlend.buf

[ResourceCharacterSkinHairTexcoord]
type = Buffer
stride = 20
filename = CharacterSkinHairTexcoord.buf

[ResourceCharacterSkinHairAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = CharacterSkinHairA.ib

[ResourceCharacterSkinHairBIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = CharacterSkinHairB.ib

[ResourceCharacterSkinBodyADiffuse]
filename = ./Textures/OG/CharacterSkinBodyADiffuse.dds

[ResourceCharacterSkinBodyANormalMap]
filename = ./Textures/OG/CharacterSkinBodyANormalMap.dds

[ResourceCharacterSkinBodyALightMap]
filename = ./Textures/OG/CharacterSkinBodyALightMap.dds

[ResourceCharacterSkinBodyAMaterialMap]
filename = ./Textures/OG/CharacterSkinBodyAMaterialMap.dds

[ResourceCharacterSkinDressADiffuse]
filename = ./Textures/OG/CharacterSkinDressADiffuse.dds

[ResourceCharacterSkinDressANormalMap]
filename = ./Textures/OG/CharacterSkinDressANormalMap.dds

[ResourceCharacterSkinDressALightMap]
filename = ./Textures/OG/CharacterSkinDressALightMap.dds

[ResourceCharacterSkinDressAMaterialMap]
filename = ./Textures/OG/CharacterSkinDressAMaterialMap.dds

[ResourceCharacterSkinHairADiffuse]
filename = ./Textures/OG/CharacterSkinHairADiffuse.dds

[ResourceCharacterSkinHairANormalMap]
filename = ./Textures/OG/CharacterSkinHairANormalMap.dds

[ResourceCharacterSkinHairALightMap]
filename = ./Textures/OG/CharacterSkinHairALightMap.dds

[ResourceCharacterSkinHairAMaterialMap]
filename = ./Textures/OG/CharacterSkinHairAMaterialMap.dds

; Extra Textures

[ResourceCharacterSkinBodyADiffuse_Black]
filename = ./Textures/Extra/CharacterSkinBodyADiffuse_Black.dds

[ResourceCharacterSkinDressADiffuse_Black]
filename = ./Textures/Extra/CharacterSkinDressADiffuse_Black.dds

[ResourceCharacterSkinExtraDiffuse]
filename = ./Textures/Extra/CharacterSkinExtraDiffuse.dds

[ResourceCharacterSkinExtraNormalMap]
filename = ./Textures/Extra/CharacterSkinExtraNormalMap.dds

[ResourceCharacterSkinExtraLightMap]
filename = ./Textures/Extra/CharacterSkinExtraLightMap.dds

[ResourceCharacterSkinExtraMaterialMap]
filename = ./Textures/Extra/CharacterSkinExtraMaterialMap.dds

; Tail Textures

[ResourceCharacterSkinTailDiffuse]
filename = ./Textures/Extra/CharacterSkinTailDiffuse.dds

[ResourceCharacterSkinTailNormalMap]
filename = ./Textures/Extra/CharacterSkinTailNormalMap.dds

[ResourceCharacterSkinTailLightMap]
filename = ./Textures/Extra/CharacterSkinTailLightMap.dds

[ResourceCharacterSkinTailMaterialMap]
filename = ./Textures/Extra/CharacterSkinTailMaterialMap.dds

; ---------------------------------------------------------
;                  Help Menu
; ---------------------------------------------------------

; =======================================
; 1) Define the color/box parameters
; =======================================

[ResourceParamsFull]
type = StructuredBuffer
array = 1
data = R32_FLOAT   -0.9 -0.9 0.9 0.9    0.85 0.7 0.1 1.0   0.33 0.32 0.18 0.95  0.02 0.02    1 2   0   1.0

[ResourceParamsHalf]
type = StructuredBuffer
array = 1
data = R32_FLOAT   -0.9 -0.9 0.9 0.9    0.85 0.7 0.1 1.0   0.33 0.32 0.18 0.95  0.02 0.02    1 2   0   1.5

[ResourceParamsDouble]
type = StructuredBuffer
array = 1
data = R32_FLOAT   -0.9 -0.9 0.9 0.9    0.85 0.7 0.1 1.0   0.33 0.32 0.18 0.95  0.02 0.02    1 2   0   2.0

; =======================================
;    One for each combo of modes.
;    Each chunk of text is the entire help text.
; =======================================

; Lock Toggles=Disabled

[ResourceLT0]
type = buffer
format = R8_UINT
filename = HelpMenu/LT0.txt

; Lock Toggles=Enabled

[ResourceLT1]
type = buffer
format = R8_UINT
filename = HelpMenu/LT1.txt

[ResourcePopLockToggles0]
type = buffer
format = R8_UINT
filename = HelpMenu/popLockToggles0.txt

[ResourcePopLockToggles1]
type = buffer
format = R8_UINT
filename = HelpMenu/popLockToggles1.txt

; =======================================
; 	  CommandListHelp
;    This picks the correct resource
;    then draws it.
; =======================================

[CommandListHelpUpdate]
; If statements to load the correct resource
if $helpVisible == 1
    if $lock == 0
        post Resource\ShaderFixes\help.ini\Help = ref ResourceLT0
    endif

    if $lock == 1
        post Resource\ShaderFixes\help.ini\Help = ref ResourceLT1
    endif
else
    ; Small pop-up when switching modes
    if $detect_lock == 1
        if $lock == 0
            post Resource\ShaderFixes\help.ini\Help = ref ResourcePopLockToggles0
        else if $lock == 1
            post Resource\ShaderFixes\help.ini\Help = ref ResourcePopLockToggles1
        endif
    endif
    $detect_lock = 0
    $menuTimeout = TIME
    $menuOff = 0
endif

; Load the color/box parameters
if $helpScale == 1
    post Resource\ShaderFixes\help.ini\Params = ref ResourceParamsFull
else if $helpScale == 2
    post Resource\ShaderFixes\help.ini\Params = ref ResourceParamsDouble
else
    post Resource\ShaderFixes\help.ini\Params = ref ResourceParamsHalf
endif
post run = CustomShader\ShaderFixes\help.ini\FormatText

[CommandListHelp]
if $helpVisible == 0
    $helpVisible = 1
    pre run = CommandListHelpUpdate

    ; Setting short help to null to avoid auto-timeout
    pre Resource\ShaderFixes\help.ini\HelpShort = null

    ; Turn off help if toggled again
    post Resource\ShaderFixes\help.ini\Help = null
endif
